### ISSUE TITLE
This Is A JRE Not JDK

### ISSUE THREAD

**Issue by opticyclic** [mishac/ansible-java#1]
This is installing a JRE not a JDK which makes it fairly useless as a Jenkins slave as you can't compile anything.

**Comment by mishac** [comment]
My intention was to use the docker image to run ansible playbooks, keeping the ansible config separate from the Jenkins server.  If you want to be compiling Java code, you'd probably be better off starting with one of the official JRE docker images, rather than starting from an Ansible image.

**Comment by opticyclic** [comment]
Maybe update the readme to indicate this then because the assumption about it being a jenkins slave with java is that a JDK would be included.

**Comment by mishac** [comment]
That's not a bad idea. Will do!
